/**
 * Códigos de error estables. El frontend decide mensajes/acciones a partir
 * de `code`, nunca parseando `message`.
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PROFESSIONAL_PROFILE_REQUIRED: 'PROFESSIONAL_PROFILE_REQUIRED',
  PROFESSIONAL_PROFILE_EXISTS: 'PROFESSIONAL_PROFILE_EXISTS',
  INVALID_REQUEST_STATE: 'INVALID_REQUEST_STATE',
  INVALID_QUOTE_STATE: 'INVALID_QUOTE_STATE',
  INVITATION_LIMIT_REACHED: 'INVITATION_LIMIT_REACHED',
  PROFESSIONAL_NOT_ELIGIBLE: 'PROFESSIONAL_NOT_ELIGIBLE',
  CANNOT_INVITE_SELF: 'CANNOT_INVITE_SELF',
  NOT_INVITED: 'NOT_INVITED',
  QUOTE_ALREADY_EXISTS: 'QUOTE_ALREADY_EXISTS',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  VERIFICATION_ALREADY_ACTIVE: 'VERIFICATION_ALREADY_ACTIVE',
  INVALID_DOCUMENT: 'INVALID_DOCUMENT',
  UPLOADS_NOT_CONFIGURED: 'UPLOADS_NOT_CONFIGURED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
