FROM node:24-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY angular.json tsconfig*.json .postcssrc.json ngsw-config.json ./
COPY src ./src
COPY public ./public

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "1000"]
